import { Poppins } from "next/font/google";
import "./globals.css";

// Load Google Font
const poppins = Poppins({
  subsets: [ "latin" ],
  display: "swap",
  variable: "--font-poppins",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900"
  ]
});

// You can add more fonts if needed like Geist or Geist Mono

export const metadata = {
  title: "Test for Jobwhee - Figma",
  description: "Generated by create next app",
};

export default function RootLayout ({ children })
{
  return (
    <html data-arp="" lang="en">
      <body className={`${ poppins.variable } PoppinsFont antialiased`}>
        {children}
      </body>
    </html>
  );
}
